### ISSUE TITLE
Loading keypair from env file doesn't work on current version

### ISSUE THREAD

**Issue by matzayonc** [solana-developers/professional-education#7]
When package-lock.json is deleted and recreated the `load-keypair.ts` doesn't recognise keys. 
The same when creating a new repository, and installing dependencies.

**Comment by mikemaccana** [comment]
Hey @matzayonc ! This should be fixed with the current version of `@solana-developers/helpers` - can you please `npm install @solana-developers/helpers@latest` and re-test?

**Comment by matzayonc** [comment]
Hey, @mikemaccana. I checked it for the latest version and can confirm it works great now. Thanks!

**Comment by matzayonc** [comment]
Successfully solved upstream
